/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BiryaniRouteImport } from './routes/biryani'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PlaceOrderRouteImport } from './routes/place-order'
import { Route as ProteinsRouteImport } from './routes/proteins'
import { Route as QrRouteImport } from './routes/qr'
import { Route as TraysRouteImport } from './routes/trays'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCmsRouteImport } from './routes/admin/cms'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDailyControlRouteImport } from './routes/admin/daily-control'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProteinsRouteImport } from './routes/admin/proteins'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BiryaniRoute = BiryaniRouteImport.update({
  id: '/biryani',
  path: '/biryani',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceOrderRoute = PlaceOrderRouteImport.update({
  id: '/place-order',
  path: '/place-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteinsRoute = ProteinsRouteImport.update({
  id: '/proteins',
  path: '/proteins',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const TraysRoute = TraysRouteImport.update({
  id: '/trays',
  path: '/trays',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDailyControlRoute = AdminDailyControlRouteImport.update({
  id: '/admin/daily-control',
  path: '/admin/daily-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/admin/delivery',
  path: '/admin/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProteinsRoute = AdminProteinsRouteImport.update({
  id: '/admin/proteins',
  path: '/admin/proteins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/biryani': typeof BiryaniRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/delivery': typeof DeliveryRoute
  '/menu': typeof MenuRoute
  '/place-order': typeof PlaceOrderRoute
  '/proteins': typeof ProteinsRoute
  '/qr': typeof QrRoute
  '/trays': typeof TraysRoute
  '/validation': typeof ValidationRoute
  '/welcome': typeof WelcomeRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/daily-control': typeof AdminDailyControlRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/proteins': typeof AdminProteinsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/biryani': typeof BiryaniRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/delivery': typeof DeliveryRoute
  '/menu': typeof MenuRoute
  '/place-order': typeof PlaceOrderRoute
  '/proteins': typeof ProteinsRoute
  '/qr': typeof QrRoute
  '/trays': typeof TraysRoute
  '/validation': typeof ValidationRoute
  '/welcome': typeof WelcomeRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/daily-control': typeof AdminDailyControlRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/proteins': typeof AdminProteinsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/biryani': typeof BiryaniRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/delivery': typeof DeliveryRoute
  '/menu': typeof MenuRoute
  '/place-order': typeof PlaceOrderRoute
  '/proteins': typeof ProteinsRoute
  '/qr': typeof QrRoute
  '/trays': typeof TraysRoute
  '/validation': typeof ValidationRoute
  '/welcome': typeof WelcomeRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/daily-control': typeof AdminDailyControlRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/proteins': typeof AdminProteinsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/biryani'
    | '/cart'
    | '/checkout'
    | '/confirmation'
    | '/contact'
    | '/customize'
    | '/delivery'
    | '/menu'
    | '/place-order'
    | '/proteins'
    | '/qr'
    | '/trays'
    | '/validation'
    | '/welcome'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/daily-control'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/proteins'
    | '/admin/reports'
    | '/admin/'
    | '/admin/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/biryani'
    | '/cart'
    | '/checkout'
    | '/confirmation'
    | '/contact'
    | '/customize'
    | '/delivery'
    | '/menu'
    | '/place-order'
    | '/proteins'
    | '/qr'
    | '/trays'
    | '/validation'
    | '/welcome'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/daily-control'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/proteins'
    | '/admin/reports'
    | '/admin'
    | '/admin/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/biryani'
    | '/cart'
    | '/checkout'
    | '/confirmation'
    | '/contact'
    | '/customize'
    | '/delivery'
    | '/menu'
    | '/place-order'
    | '/proteins'
    | '/qr'
    | '/trays'
    | '/validation'
    | '/welcome'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/daily-control'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/proteins'
    | '/admin/reports'
    | '/admin/'
    | '/admin/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BiryaniRoute: typeof BiryaniRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  CustomizeRoute: typeof CustomizeRoute
  DeliveryRoute: typeof DeliveryRoute
  MenuRoute: typeof MenuRoute
  PlaceOrderRoute: typeof PlaceOrderRoute
  ProteinsRoute: typeof ProteinsRoute
  QrRoute: typeof QrRoute
  TraysRoute: typeof TraysRoute
  ValidationRoute: typeof ValidationRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDailyControlRoute: typeof AdminDailyControlRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProteinsRoute: typeof AdminProteinsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biryani': {
      id: '/biryani'
      path: '/biryani'
      fullPath: '/biryani'
      preLoaderRoute: typeof BiryaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place-order': {
      id: '/place-order'
      path: '/place-order'
      fullPath: '/place-order'
      preLoaderRoute: typeof PlaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proteins': {
      id: '/proteins'
      path: '/proteins'
      fullPath: '/proteins'
      preLoaderRoute: typeof ProteinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trays': {
      id: '/trays'
      path: '/trays'
      fullPath: '/trays'
      preLoaderRoute: typeof TraysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/daily-control': {
      id: '/admin/daily-control'
      path: '/admin/daily-control'
      fullPath: '/admin/daily-control'
      preLoaderRoute: typeof AdminDailyControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proteins': {
      id: '/admin/proteins'
      path: '/admin/proteins'
      fullPath: '/admin/proteins'
      preLoaderRoute: typeof AdminProteinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BiryaniRoute: BiryaniRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  CustomizeRoute: CustomizeRoute,
  DeliveryRoute: DeliveryRoute,
  MenuRoute: MenuRoute,
  PlaceOrderRoute: PlaceOrderRoute,
  ProteinsRoute: ProteinsRoute,
  QrRoute: QrRoute,
  TraysRoute: TraysRoute,
  ValidationRoute: ValidationRoute,
  WelcomeRoute: WelcomeRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDailyControlRoute: AdminDailyControlRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProteinsRoute: AdminProteinsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
